### ISSUE TITLE
Pre-processed features of COCO link is broken

### ISSUE THREAD

**Issue by varadbhogayata** [varunagrawal/VisualQA#1]
I want to execute the code. Could you please provide the pre-processed features.

**Comment by varunagrawal** [comment]
Thanks for reporting this @varadbhogayata. I had planned to do this but got busy with other stuff. Let me fix this now.

**Comment by varunagrawal** [comment]
Done. Please find the link in the README. It should be operational now.

**Comment by varadbhogayata** [comment]
Thank you very much! Could you please provide the trained model weights to check the demo.

**Comment by varadbhogayata** [comment]
Thank you very much!

**Comment by varunagrawal** [comment]
Okay this is kinda late and I hope you figured this out yourself.
I have uploaded the new preprocessed features and confirm they work well.
