### ISSUE TITLE
train errors

### ISSUE THREAD

**Issue by gushart** [varunagrawal/VisualQA#5]
Hello! I've got the same problem as this [pickle problem](https://github.com/varunagrawal/VisualQA/issues/2#issue-318190554)
when I use vgg embeds:
`_pickle.UnpicklingError: invalid load key, '\x0d'.
`

Also there are one more error when I tryed to use resnet embeds.
`
RuntimeError: size mismatch, m1: [16 x 2048], m2: [4096 x 1024] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266
`

ps. running as python3 main.py
pss. embeddings downloaded by makefile in image_embeddings

**Comment by varunagrawal** [comment]
I have just updated the image embeddings and uploaded them again. Can you please delete all the old ones and download the new ones? The same `make resnet152` process should work.

**Comment by varunagrawal** [comment]
Closing due to lack on response.
